import { InsertPlant } from '@shared/schema';

export const gardenPlantData: InsertPlant[] = [
  // High Line Plants
  {
    name: "Purple Coneflower",
    scientificName: "Echinacea purpurea",
    description: "A popular perennial with purple-pink flowers and a cone-shaped center. Attracts butterflies and birds, drought-resistant once established.",
    imageUrl: "https://i.pinimg.com/originals/96/40/14/964014d21068ed2dfa8f8242c8d363cf.gif",
    lightLevel: "bright",
    waterNeeds: "medium",
    difficultyLevel: "beginner",
    growZone: "3-9",
    temperature: "Tolerates heat and cold, hardy in zones 3-9",
    humidity: "Adaptable to average outdoor humidity",
    careInstructions: "Deadhead to prolong blooming. Divide every 3-4 years. Leave seed heads for winter interest and bird food.",
    commonIssues: "Powdery mildew: may appear in humid conditions. Japanese beetles: can damage foliage."
  },
  {
    name: "Switchgrass",
    scientificName: "Panicum virgatum",
    description: "A native ornamental grass with airy seed heads and excellent fall color. Provides winter interest and habitat for birds.",
    imageUrl: "https://thumbs.gfycat.com/ScornfulJampackedAegeancat-size_restricted.gif",
    lightLevel: "bright",
    waterNeeds: "medium",
    difficultyLevel: "beginner",
    growZone: "4-9",
    temperature: "Heat and drought tolerant once established",
    humidity: "Adaptable to average outdoor conditions",
    careInstructions: "Cut back to 4-6 inches in late winter before new growth appears. Divide clumps every 3-4 years if needed.",
    commonIssues: "Rust: may occur in humid conditions. Leaf spot: keep foliage dry when watering."
  },
  {
    name: "Russian Sage",
    scientificName: "Perovskia atriplicifolia",
    description: "A woody subshrub with aromatic silver-gray foliage and lavender-blue flowers. Drought-tolerant and deer-resistant.",
    imageUrl: "https://i.pinimg.com/originals/d9/fd/17/d9fd177af462f8b28aa3fe4b320a8555.gif",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "4-9",
    temperature: "Heat and drought tolerant, prefers full sun locations",
    humidity: "Prefers dry conditions; excessive humidity can cause issues",
    careInstructions: "Cut back to 6 inches in early spring. Provide excellent drainage. No fertilizer needed for established plants.",
    commonIssues: "Root rot: can occur in poorly drained soils. Dieback: may occur in cold, wet winters."
  },
  {
    name: "Black-Eyed Susan",
    scientificName: "Rudbeckia fulgida",
    description: "A cheerful perennial with golden-yellow petals and dark centers. Attracts pollinators and provides long-lasting color.",
    imageUrl: "https://i.pinimg.com/originals/ec/80/d5/ec80d559bc1013a53b07e5896821f633.gif",
    lightLevel: "bright",
    waterNeeds: "medium",
    difficultyLevel: "beginner",
    growZone: "4-9",
    temperature: "Heat tolerant, relatively cold hardy in appropriate zones",
    humidity: "Adaptable to various humidity levels",
    careInstructions: "Deadhead to promote continuous blooming. Divide every 3-4 years. May self-seed.",
    commonIssues: "Powdery mildew: common in humid conditions. Leaf spot: keep foliage dry when watering."
  },
  {
    name: "Prairie Dropseed",
    scientificName: "Sporobolus heterolepis",
    description: "A fine-textured native grass with elegant, arching foliage and airy seed heads. Excellent fall color and winter interest.",
    imageUrl: "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXFmcjUxeTU2eG16anpwaDZ3aGUxcG92Mzg4MXBqanNyemloaHk3MiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o6gbchrcNDs2ySuYw/giphy.gif",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "3-9",
    temperature: "Very cold hardy and heat tolerant",
    humidity: "Prefers dry to average conditions",
    careInstructions: "Cut back in late winter or early spring. Divide infrequently, as plants are slow to establish.",
    commonIssues: "Few pest or disease problems. Leaf spot: may occur in extremely wet conditions."
  },
  
  // Proven Winners Plants
  {
    name: "Diamond Frost Euphorbia",
    scientificName: "Euphorbia hypericifolia",
    description: "A cloud-like plant with tiny white flowers that bloom continuously. Heat and drought tolerant annual that pairs well with other plants.",
    imageUrl: "https://www.gifpng.com/thumb/plant/2jvGMO-plant-transparent-gif.gif",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "10-11",
    temperature: "Prefers warm conditions; treat as annual in zones below 10",
    humidity: "Adaptable, but prefers lower humidity",
    careInstructions: "No deadheading required. Fertilize lightly. Trim back if needed to shape.",
    commonIssues: "Root rot: can occur in overly wet conditions. Note: sap may cause skin irritation."
  },
  {
    name: "Sweet Caroline Sweetheart Potato Vine",
    scientificName: "Ipomoea batatas",
    description: "A trailing ornamental sweet potato with heart-shaped leaves in shades of lime to burgundy. Excellent for containers and ground cover.",
    imageUrl: "https://www.pikpng.com/pngl/b/45-451637_vine-png-vine-plant-transparent-background-clipart.png",
    lightLevel: "bright",
    waterNeeds: "medium",
    difficultyLevel: "beginner",
    growZone: "9-11",
    temperature: "Loves heat, sensitive to frost",
    humidity: "Adaptable to various humidity levels",
    careInstructions: "Keep evenly moist. Fertilize monthly during growing season. Trim as needed to control growth.",
    commonIssues: "Deer browse: may attract deer. Leaf scorch: can occur in too much direct sun in hot climates."
  },
  {
    name: "Little Bluestem",
    scientificName: "Schizachyrium scoparium",
    description: "A native grass with blue-green summer foliage that turns copper-orange in fall. Provides excellent winter interest.",
    imageUrl: "https://images.unsplash.com/photo-1632422716048-a9ca9287056a?ixlib=rb-4.0.1&auto=format&fit=crop&w=800&q=80",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "3-9",
    temperature: "Very cold hardy and heat tolerant",
    humidity: "Prefers lower humidity, good air circulation",
    careInstructions: "Cut back in late winter. Grows best in poor to moderately fertile soil; avoid rich soil.",
    commonIssues: "Lodging: may flop in rich soil or part shade. Rust: occasionally affects foliage."
  },
  {
    name: "Cat's Pajamas Catmint",
    scientificName: "Nepeta x faassenii",
    description: "A compact catmint with indigo-blue flowers from soil to tips. Attracts pollinators and resists deer and rabbits.",
    imageUrl: "https://cdn.shopify.com/s/files/1/0059/8835/2052/products/Cats_Pajamas_Catmint_1_FGT_1024x1024.jpg?v=1627647451",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "3-8",
    temperature: "Cold hardy and heat tolerant",
    humidity: "Prefers dry to average conditions",
    careInstructions: "Shear back by 1/3 after first bloom for rebloom. Cut back in late fall or early spring.",
    commonIssues: "Crown rot: can occur in poorly drained soils. Japanese beetles: may occasionally feed on foliage."
  },
  {
    name: "Lemon Coral Sedum",
    scientificName: "Sedum mexicanum",
    description: "A bright chartreuse succulent with needle-like foliage. Drought-tolerant and works well in containers or as ground cover.",
    imageUrl: "https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-g-sedum-mexicanum-lemon-coral-plant.jpg?v=1655412358",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "7-10",
    temperature: "Heat tolerant, protect from frost in colder zones",
    humidity: "Prefers dry conditions",
    careInstructions: "Allow soil to dry between waterings. Trim back if growth becomes leggy. Protect from winter wet in colder zones.",
    commonIssues: "Root rot: common in poorly drained soil. Scale insects: occasional pest."
  },
  
  // Bluestone Perennials
  {
    name: "Millenium Allium",
    scientificName: "Allium 'Millenium'",
    description: "A butterfly magnet with globe-shaped purple flowers over neat clumps of glossy green foliage. Deer and rabbit resistant.",
    imageUrl: "https://www.gardenia.net/storage/app/public/uploads/images/detail/Allium%20Millenium.jpg",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "5-9",
    temperature: "Heat tolerant, cold hardy within its zone range",
    humidity: "Adaptable, prefers good air circulation",
    careInstructions: "Remove spent flowers. Divide in spring or fall when clumps become crowded. Maintain good drainage.",
    commonIssues: "Onion fly: rarely a problem in ornamental alliums. Leaf streak: may occur in wet conditions."
  },
  {
    name: "Jack Frost Brunnera",
    scientificName: "Brunnera macrophylla 'Jack Frost'",
    description: "A shade-loving perennial with silver leaves veined in green and sprays of bright blue forget-me-not flowers in spring.",
    imageUrl: "https://cdn.shopify.com/s/files/1/0059/8835/2052/products/Jack_Frost_Brunnera_10.6_FGT_1024x1024.jpg?v=1591636583",
    lightLevel: "low",
    waterNeeds: "medium",
    difficultyLevel: "intermediate",
    growZone: "3-8",
    temperature: "Prefers cooler temperatures; protect from hot afternoon sun",
    humidity: "Prefers moderate to high humidity",
    careInstructions: "Keep consistently moist, especially in heat. Remove damaged leaves as needed. Divide every 2-3 years.",
    commonIssues: "Leaf scorch: can occur in too much sun or heat. Slugs and snails: may damage foliage."
  },
  {
    name: "Karl Foerster Feather Reed Grass",
    scientificName: "Calamagrostis x acutiflora",
    description: "An upright, clump-forming grass with feathery plumes that emerge reddish-pink and mature to golden tan. Provides winter interest.",
    imageUrl: "https://cdn.shopify.com/s/files/1/0089/3075/4665/products/calamagrostis-x-acutiflora-karl-foerster.jpg?v=1620228743",
    lightLevel: "bright",
    waterNeeds: "medium",
    difficultyLevel: "beginner",
    growZone: "4-9",
    temperature: "Tolerates heat and cold within its zone range",
    humidity: "Adaptable to various humidity levels",
    careInstructions: "Cut back to a few inches above ground in late winter. Divide every 2-3 years if center dies out.",
    commonIssues: "Rust: may occur in humid conditions. Lodging: may flop in too much shade or rich soil."
  },
  {
    name: "Walker's Low Catmint",
    scientificName: "Nepeta x faassenii",
    description: "A long-blooming perennial with gray-green foliage and lavender-blue flowers. Attracts pollinators and resists deer and rabbits.",
    imageUrl: "https://cdn.shopify.com/s/files/1/0059/8835/2052/products/Catmint_Walkers_Low_1_FGT_1024x1024.jpg?v=1618590728",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "4-8",
    temperature: "Heat tolerant and cold hardy in appropriate zones",
    humidity: "Prefers dry to average conditions",
    careInstructions: "Shear back by half after first bloom to encourage rebloom. Cut back in fall or early spring.",
    commonIssues: "Crown rot: can occur in wet, poorly drained soil. Spider mites: may occur in hot, dry conditions."
  },
  {
    name: "Husker Red Penstemon",
    scientificName: "Penstemon digitalis",
    description: "A native perennial with burgundy foliage and white tubular flowers on red stems. Attracts hummingbirds and butterflies.",
    imageUrl: "https://cdn11.bigcommerce.com/s-csqyj/images/stencil/1280x1280/products/1394/3231/penstemon_husker_red_4__86915.1553797941.jpg?c=2",
    lightLevel: "bright",
    waterNeeds: "low",
    difficultyLevel: "beginner",
    growZone: "3-8",
    temperature: "Heat and drought tolerant once established",
    humidity: "Prefers low to moderate humidity",
    careInstructions: "Deadhead for continued bloom. Cut back in late fall or early spring. Provide excellent drainage.",
    commonIssues: "Leaf spot: can occur in humid conditions. Root rot: problematic in poorly drained soils."
  }
];